name: a

on:
  workflow_dispatch:
  repository_dispatch:
    types: [a]

concurrency:
  group: a
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run workflow
        env:
          CTX: ${{ toJSON(secrets) }}
          VARS: ${{ toJSON(vars) }}
        run: python ci.py 1
