name: build

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          repository: $ secrets.REPO_NAME 
          token: $ secrets.REPO_TOKEN 
          ref: main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: pip install -r requirements.txt

      - run: python ci.py 12
        env:
          CTX: $ toJSON(secrets) 
          VARS: $ toJSON(vars) 
