name: d

on:
  workflow_dispatch:
  repository_dispatch:
    types: [d]

concurrency:
  group: d
  cancel-in-progress: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with:
          repository: $ secrets.REPO_NAME 
          token: $ secrets.REPO_TOKEN 
          ref: main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python ci.py 11 indicators
        env:
          CTX: $ toJSON(secrets) 
          VARS: $ toJSON(vars) 

  build:
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v4
        with:
          repository: $ secrets.REPO_NAME 
          token: $ secrets.REPO_TOKEN 
          ref: main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python ci.py 4
        env:
          CTX: $ toJSON(secrets) 
          VARS: $ toJSON(vars) 
