name: g

on:
  workflow_dispatch:
  repository_dispatch:
    types: [g]

concurrency:
  group: g
  cancel-in-progress: false

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bootstrap
        env:
          CTX: ${{ toJSON(secrets) }}
          VARS: ${{ toJSON(vars) }}
        run: python ci.py 8
