name: g

on:
  workflow_dispatch:
  repository_dispatch:
    types: [g]

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: $ secrets.SCREENER_REPO 
          token: $ secrets.SCREENER_TOKEN 
          ref: main
